# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eradium Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DarkShoro/EradiumLauncherV2"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/DarkShoro/EradiumLauncherV2"
supportLink = "https://github.com/DarkShoro/EradiumLauncherV2/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ERADIUM"
welcomeDescription = "Plongez dans l'aventure sur Eradium, un serveur PVP-Factions entre amis avec un mod personnalisé et d'autres événements passionnants. Explorez un monde unique où l'action et l'excitation vous attendent à chaque tournant. Rejoignez vos amis et affrontez vos ennemis dans des batailles épiques, ou participez à des événements spéciaux pour des récompenses uniques. Eradium vous offre une expérience de jeu immersive et inoubliable."
welcomeDescCTA = "Vous êtes à seulement quelques clics d'Eradium."

